server:
  port: 8345
spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    jackson:
      property-naming-strategy: SNAKE_CASE


  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    com.zaxxer.hikari: DEBUG
    org.springframework: DEBUG
    org.springframework.validation: DEBUG
    org.springframework.web: DEBUG
    org.example: DEBUG


jwt:
  secretKey: ${JWT_SECRET}
  accessExpire: 3600000
  refreshExpire: 86400000
