server:
  port: 8345
spring:
  security:
    user:
      name: admin
      password: admin1234!
  datasource:
    url: jdbc:mariadb://svc.sel4.cloudtype.app:31245/Haso
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

    jackson:
      property-naming-strategy: SNAKE_CASE


  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    com.zaxxer.hikari: DEBUG
    org.springframework: DEBUG
    org.springframework.validation: DEBUG
    org.springframework.web: DEBUG
    org.example: DEBUG


jwt:
  accessExpire: 3600000
  refreshExpire: 86400000
  expiration: 86400000
  secret-key: vObSBDYqvJfXJ3xOCMwDqNCe/UzQ5Xt1C5v2a3Tq5cM=



file:
  dir: /Users/dgsw8th57/Desktop/store

api:
  serviceKey: "9En4mQjBmqmTfpGrjISU5Il7TDZOFpCfw543RYFR6/egec191fhfSFyWYfCoGks/mGN3csv63C8b4caRXJdLog=="
  url: "https://api.odcloud.kr/api/nts-businessman/v1/validate"
