server:
  port: 8345


spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    jackson:
      property-naming-strategy: SNAKE_CASE

  security:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET, POST, PUT, DELETE"
      allowed-headers: "*"
      exposed-headers: "Authorization"
      max-age: 3600


  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: INFO
    com.zaxxer.hikari: INFO
    org.springframework: WARN
    org.springframework.web: WARN
    org.example: DEBUG



jwt:
  accessExpire: 3600000
  refreshExpire: 86400000
  expiration: 86400000
  secret-key: ${JWT_SECRET}



file:
  dir: s3://haso-bucket/store

api:
  serviceKey: ${OPEN_API_KEY}
  url: "https://api.odcloud.kr/api/nts-businessman/v1/validate"



cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    s3:
      bucketName: haso-bucket
      region:
        staticRegion: ap-northeast-2
      stack:
        auto: false









