server:
  port: 8345
spring:
  datasource:
    url: jdbc:mariadb://svc.sel4.cloudtype.app:31245/Haso
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

    jackson:
      property-naming-strategy: SNAKE_CASE


  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    com.zaxxer.hikari: DEBUG
    org.springframework: DEBUG
    org.springframework.validation: DEBUG
    org.springframework.web: DEBUG
    org.example: DEBUG


jwt:
  secretKey: xW8@!v1kA5#L3mD9rQ7vZ*JzT2uF6gR!0pHqY3wD#Ls@8&Nx0V9jS$K
  accessExpire: 3600000
  refreshExpire: 86400000
